// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
///...
///await Firebase.initializeApp(
///options: DefaultFirebaseOptions.currentPlatform,
// );
//```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_7t8_ESlN0TVdXzZ4XvGP8t4pTKToQco',
    appId: '1:290778671583:web:9b02bebabbd7e89bd8fc6a',
    messagingSenderId: '290778671583',
    projectId: 'attendance-740c8',
    authDomain: 'attendance-740c8.firebaseapp.com',
    storageBucket: 'attendance-740c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHVFl06cCXgB9CIxJboS_GTOALbAEm6Yw',
    appId: '1:290778671583:android:6cd38c89a03ecdedd8fc6a',
    messagingSenderId: '290778671583',
    projectId: 'attendance-740c8',
    storageBucket: 'attendance-740c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx0jdCpPZalKWLCk_5rYT99WMI7x7Yg7M',
    appId: '1:290778671583:ios:a6f0c041b4c5500cd8fc6a',
    messagingSenderId: '290778671583',
    projectId: 'attendance-740c8',
    storageBucket: 'attendance-740c8.appspot.com',
    iosBundleId: 'com.domart.attendance',
  );
}
